### ISSUE TITLE
Support seeding works

### ISSUE THREAD

**Issue by derat** [derat/yambs#10]
As mentioned in https://github.com/derat/yambs/issues/2#issuecomment-1397294024, it'd be nice to be able to seed the "Add Work" form (including relationships) using URLs like <https://test.musicbrainz.org/work/create?edit-work.name=Test&rels.0.type=a255bca1-b157-4518-9108-7b147dc3fc68&rels.0.target=7e84f845-ac16-41fe-9ff8-df12eb32af55>.

**Comment by derat** [comment]
I'm wondering what the workflow would be for using this, since it seems like it may be a bit painful. Would a user need to first create a recording (or a bunch of recordings by creating a release), and then somehow (manually?) get the recording's MBID so they could use it to add a relationship when creating a corresponding work? It might be nice if yambs could support multi-step edits like this, but I'm not sure how feasible it'd be to actually implement.

**Comment by kellnerd** [comment]
You are right, for the typical album-based MB editing workflow this isn't really useful, the already existing _Batch-create new works_ tool in the release editor should cover most of the standard cases. But I guess it is useful for works which are not necessarily linked to recordings immediately, e.g. traditionals or complex (classical) work hierarchies.

What I had in mind specifically for this feature are audio dramas. There are whole series with dozens or even hundreds of episodes in MB of which almost none have associated works.
As the number of writers involved in a series is often limited, it would be a huge time saver to seed all missing works from a list of titles (and authors) before assigning the freshly created works to all recordings of an audio drama release (most likely to be done via the release relationship editor).

**Comment by kellnerd** [comment]
> It might be nice if yambs could support multi-step edits like this, but I'm not sure how feasible it'd be to actually implement.

I would imagine that to work by yambs adding a new column with the MBIDs of the successfully seeded entities to the existing input lines. Then the user could refine the input fields string to use different columns (which were previously excluded) to generate the next set of edits. But I don't know whether it's possible to get these MBIDs of the seeded entities, only seeded releases have a `redirect_uri` which will be called with the MBID as a query parameter as far as I know.

**Comment by derat** [comment]
I think this should be working now. Please let me know if it fills your use case (or if it doesn't). :-)

I haven't created a new release yet, but I've deployed the new code to <https://yambs.erat.org>. You should be able to try it out by selecting `Text`, `CSV`, `Work`, and then setting the input fields to `name,rel0_type,rel0_target` and the input to:

```csv
First Title,167,7e84f845-ac16-41fe-9ff8-df12eb32af55
Second Title,167,7e84f845-ac16-41fe-9ff8-df12eb32af55
```

(Relationship types can be specified as either database IDs or MBIDs.)

**Comment by derat** [comment]
> > It might be nice if yambs could support multi-step edits like this, but I'm not sure how feasible it'd be to actually implement.
> 
> I would imagine that to work by yambs adding a new column with the MBIDs of the successfully seeded entities to the existing input lines. Then the user could refine the input fields string to use different columns (which were previously excluded) to generate the next set of edits. But I don't know whether it's possible to get these MBIDs of the seeded entities, only seeded releases have a `redirect_uri` which will be called with the MBID as a query parameter as far as I know.

Yeah, I'm (ab)using `redirect_uri` to make it easier to upload cover art after adding a new release, but it feels pretty hacky and I haven't seen anything similar for other entity types. Even if there were some way to get the new MBIDs, it might be a pretty big challenge (from both a programming and UI perspective) to collect the results from multiple edits that the user completes piecemeal and then use them to generate a new set of seeded edits.

**Comment by kellnerd** [comment]
Great work, thanks a lot! I wanted to be able to seed works for a few years by now, but was too lazy to implement it myself. Now I've quite a bit of work ahead, I will give you some feedback once I've assembled a first spreadsheet with data :)

P.S. Not publishing a new release apparently also results in https://pkg.go.dev/github.com/derat/yambs/seed#Language not being up-to-date, some of the linked sections are missing because the page was last updated in November.

**Comment by derat** [comment]
> P.S. Not publishing a new release apparently also results in https://pkg.go.dev/github.com/derat/yambs/seed#Language not being up-to-date, some of the linked sections are missing because the page was last updated in November.

I noticed that the other day too. There's some discussion at https://github.com/golang/go/issues/38848 and https://github.com/golang/go/issues/37106, but it sounds like accessing <https://pkg.go.dev/github.com/derat/yambs/seed@main> may trigger a refresh -- I can see that that URL currently shows db1e9e5 from yesterday. I'll change the documentation URLs to point at `@main` so they'll hopefully at least always reference the latest version that pkg.go.dev has indexed.

**Comment by derat** [comment]
Visiting that URL looks like it did the trick: the `@main` URL now shows 6987704, so it includes all of the new work-related types.

**Comment by kellnerd** [comment]
After having tested a more advanced example, everything is working as expected so far 👍

Only one thing seems to be missing: I'm not able to seed the "Credited as" field of the relationship's target entity. Similar to relationship attributes' credited-as text, I would expect to be able to seed this, but apparently this is currently not possible at all.
I've created a ticket to request this feature: [MBS-12849](https://tickets.metabrainz.org/browse/MBS-12849)

**Comment by derat** [comment]
Great to hear! Please let me know if you run into any problems further along.

And thanks for filing the "credited as" ticket; I've added it to my watchlist and will add support for setting those parameters if/when the server exposes them.

**Comment by derat** [comment]
[MBS-12849](https://tickets.metabrainz.org/browse/MBS-12849) has been fixed now, so I've added `rel*_source_credit` and `rel*_target_credit` fields. They work from my limited testing, but please let me know if you notice any issues.
