### ISSUE TITLE
Get copyright details, label info, and barcodes from Tidal

### ISSUE THREAD

**Issue by derat** [derat/yambs#23]
From `HibiscusKazeneko` at <https://community.metabrainz.org/t/announcing-yambs-yet-another-musicbrainz-seeder/608630/3>:

> I only wish it pulled copyright details, label information and barcodes like a-tisket does; I had to fill in the gaps using [TIDAL](https://xythium.github.io/tidal.html), and even that doesn’t differentiate between regular copyright and phonographic copyright much of the time.

When I run:

 ```
curl -H 'X-Tidal-Token: gsFXkJqGrUNoYMQPZe4k3WKwijnrp8iGSwn3bApe' \
  'https://api.tidal.com/v1/albums/115776759?countryCode=US'
```

I get the following (after pretty-printing):

```json
{
  "id": 115776759,
  "title": "Hollowed",
  "duration": 3307,
  "streamReady": true,
  "streamStartDate": "2016-03-18T00:00:00.000+0000",
  "allowStreaming": true,
  "premiumStreamingOnly": false,
  "numberOfTracks": 13,
  "numberOfVideos": 0,
  "numberOfVolumes": 1,
  "releaseDate": "2016-03-18",
  "copyright": "Planet Mu Records Ltd.",
  "type": "ALBUM",
  "version": null,
  "url": "http://www.tidal.com/album/115776759",
  "cover": "0c383df5-7220-4f1f-a57d-3976a5d4ea4d",
  "vibrantColor": "#FFFFFF",
  "videoCover": null,
  "explicit": false,
  "upc": "5055300385710",
  "popularity": 4,
  "audioQuality": "LOSSLESS",
  "audioModes": ["STEREO"],
  "artist": {
    "id": 4134860,
    "name": "Ital Tek",
    "type": "MAIN",
    "picture": "efe4665c-fc83-4b9c-875e-39f66a91a02d"
  },
  "artists": [
    {
      "id": 4134860,
      "name": "Ital Tek",
      "type": "MAIN",
      "picture": "efe4665c-fc83-4b9c-875e-39f66a91a02d"
    }
  ]
}
```

The UPC/barcode looks like it's easy to get; I'm not sure why I didn't include it initially (maybe the `upc` property was missing for the first album that I looked at?).

I can also grab the `copyright` property, although I'm not sure exactly what to do with it. I'm guessing that it could apply to any of the following relationship types:

```go
    // This relationship indicates the artist is the copyright holder for this
    // release, usually indicated with a © symbol.
    LinkType_Copyright_Artist_Release LinkType = 709
    // This relationship indicates the label is the copyright holder for this
    // release, usually indicated with a © symbol.
    LinkType_Copyright_Label_Release LinkType = 708
    // This relationship indicates the artist is the <a
    // href="//en.wikipedia.org/wiki/Sound_recording_copyright_symbol"
    // target="_blank">phonographic copyright</a> holder for this release, usually
    // indicated with a ℗ symbol.
    LinkType_PhonographicCopyright_Artist_Release LinkType = 710
    // This relationship indicates the label is the <a
    // href="//en.wikipedia.org/wiki/Sound_recording_copyright_symbol">phonographic
    // copyright</a> holder for this release, usually indicated with a ℗ symbol.
    LinkType_PhonographicCopyright_Label_Release LinkType = 711
```

Should I just stuff it into an annotation?

Regarding the label, if I run this:

```
curl -H 'X-Tidal-Token: gsFXkJqGrUNoYMQPZe4k3WKwijnrp8iGSwn3bApe' \
  'https://api.tidal.com/v1/albums/115776759/items/credits?countryCode=US'
```

(which is similar to what <https://xythium.github.io/tidal.html> appears to do, as opposed to the `/albums/.../tracks` endpoint that I'm currently querying), then I get objects that also contain per-track credits:

```json
{
  "limit": 10,
  "offset": 0,
  "totalNumberOfItems": 13,
  "items": [
    {
      "item": {
        "id": 115776760,
        "title": "A Delicate Balance",
        ...
      },
      "type": "track",
      "credits": [
        { "type": "Composer", "contributors": [{ "name": "A. Myson" }] },
        {
          "type": "Music Publisher",
          "contributors": [{ "name": "Planet Mu Records Ltd." }]
        }
      ]
    },
    {
      "item": {
        "id": 115776761,
        "title": "Redeemer",
        ...
```

If all of the tracks have identical `Music Publisher` credits, should it be used to seed the label field?

**Comment by cherryblossom000** [comment]
a-tisket dumps the copyright info in an annotation, so I think that’s best. That way when editors who can’t be bothered adding the proper relationships import into Tidal, the copyright info isn’t lost, and editors who can be bothered (like me) can remove the annotation if it’s redundant and add the relationships.

Music publishers are distinct from (and can be different to) labels, so I don’t think that should be used to seed the label.

**Comment by derat** [comment]
Thanks for the info! Barcodes and copyright info should be included by the web instance now (although I haven't created a new release of the command-line program yet).

Would it still be useful to include publishing credits in the annotation (if they're the same for all tracks)?

**Comment by cherryblossom000** [comment]
Credits can be viewed at e.g. https://listen.tidal.com/album/91877682/credits, so while it might be helpful to include the annotation, I’m not sure if it’s that necessary. Maybe it would be good to get some other editors’ opinions.

There’s also sometimes (quite rarely in my experience) album-level credits via the `/albums/91877682/credits` endpoint. Looks something like this:

```json
[
	{
		"type": "Producer",
		"contributors": [{"name": "Christian \"Leggy\" Langdon"}]
	},
	{
		"type": "Booking",
		"contributors": [{"name": "Dave Tamaroff"}]
	},
	{
		"type": "Cover Photo",
		"contributors": [{"name": "Brantley Gutierrez"}]
	},
	{
		"type": "Engineer",
		"contributors": [{"name": "Christian \"Leggy\" Langdon"}]
	},
	{
		"type": "Layout",
		"contributors": [{"name": "Jeff Gilligan"}]
	},
	{
		"type": "Management",
		"contributors": [
			{"name": "Christine Stauder"},
			{"name": "Kevin Morris", "id": 6489863}
		]
	},
	{
		"type": "Mastering",
		"contributors": [{"name": "Stephen Marcussen"}]
	},
	{
		"type": "Mixing",
		"contributors": [{"name": "Christian \"Leggy\" Langdon"}]
	},
	{
		"type": "Photography",
		"contributors": [{"name": "Don VanCleave"}]
	},
	{
		"type": "Primary Artist",
		"contributors": [{"name": "Meg Myers", "id": 4639366}]
	},
	{
		"type": "Record Label",
		"contributors": [{"name": "300 Entertainment"}]
	}
]
```

Sometimes there’s a `"Record Label"` credit which can be used to seed the label.

**Comment by derat** [comment]
Thanks again! Most of the albums that I've been using for testing actually include a `"Record Label"` credit containing at least one contributor, so I'll go ahead and include that too.

**Comment by derat** [comment]
Hmm, my current approach can end up adding a *lot* of labels in some cases. Here's what I get for <https://tidal.com/browse/album/55391786>:

![image](https://user-images.githubusercontent.com/40385/221413163-b6729499-e89c-4cbe-84d0-3d2965b2f1e4.png)

Is that desirable, or should I just use e.g. the first contributor in the label credit? (I don't know if Tidal orders them in any particular way.)

**Comment by derat** [comment]
I'm going to assume that _Dark Side of the Moon_ is a worst-case scenario for multiple label credits and close this.

**Comment by cherryblossom000** [comment]
Sorry for the late response. I agree, *Dark Side of the Moon* is probably one of the worst-case scenarios, and most releases have only 1 or maybe 2 labels.

**Comment by kellnerd** [comment]
Maybe this scenario happens for releases which have different labels for different regions?
Spotify/Deezer/Apple Music usually have at least two different releases for Pink Floyd albums to handle that, I don't know / didn't check whether Tidal also does that.

**Comment by derat** [comment]
The different-labels-for-different-regions theory seems plausible to me. If that's what's going on here, it looks like the Tidal API returns them all irrespective of the `countryCode` parameter, so I'm guessing there's not much I can do.
