### ISSUE TITLE
Support seeding partial dates

### ISSUE THREAD

**Issue by kellnerd** [derat/yambs#4]
Currently I have to set year and month separately if I don't know the exact day of release:
```
event0_year=2019
event0_month=11
```
I first tried to use `event0_date=2019-11` which seeded the release date as the 1st November instead of leaving the day field blank as I would have expected. It would be great if you could support these partial YYYY-MM dates without assuming the missing part to be 1.

Aside from that minor convenience issue, your seeder is doing a great job, I'm currently preparing a spreadsheet to submit 100+ download singles from an artist's website 👍

**Comment by derat** [comment]
Great suggestion, and glad to hear that you're finding it useful!

I'm about to submit a change to leave the month and day fields unset when they're not supplied. After it's in, I'll redeploy the web instance. Let me know if you're using one of the prebuilt binaries, in which case I'll also kick off a new release that includes the change.

**Comment by kellnerd** [comment]
Thank you for the fast implementation, I can confirm that the web version is working as expected now. No need to create a new release of the binaries just for me, I'm happy with the web version so far.
